services:
    db:
        image: postgres:13
        container_name: db
        restart: always
        ports:
            - 2345:5432
        env_file:
            - .env
        networks:
            - studentnetwork
        volumes:
            - pg:/var/lib/postgresql/data
    node_app:
        container_name: node_app
        build: .
        ports:
            - 5000:5000
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - studentnetwork

networks:
    studentnetwork:
        driver: bridge

volumes:
    pg: # volume para os postgres
